clear
clc 
close all

%% Data importing
% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\SEM_6\BCI\Assignment02\archive\Dataset\user_a.csv
%
% Auto-generated by MATLAB on 29-Apr-2021 10:39:18

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 113);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Class", "AF3DeltaStd", "AF3DeltaM", "AF3ThetaStd", "AF3ThetaM", "AF3AlphaStd", "AF3AlphaM", "AF3BetaStd", "AF3BetaM", "F7DeltaStd", "F7DeltaM", "F7ThetaStd", "F7ThetaM", "F7AlphaStd", "F7AlphaM", "F7BetaStd", "F7BetaM", "F3DeltaStd", "F3DeltaM", "F3ThetaStd", "F3ThetaM", "F3AlphaStd", "F3AlphaM", "F3BetaStd", "F3BetaM", "FC5DeltaStd", "FC5DeltaM", "FC5ThetaStd", "FC5ThetaM", "FC5AlphaStd", "FC5AlphaM", "FC5BetaStd", "FC5BetaM", "T7DeltaStd", "T7DeltaM", "T7ThetaStd", "T7ThetaM", "T7AlphaStd", "T7AlphaM", "T7BetaStd", "T7BetaM", "P7DeltaStd", "P7DeltaM", "P7ThetaStd", "P7ThetaM", "P7AlphaStd", "P7AlphaM", "P7BetaStd", "P7BetaM", "O1DeltaStd", "O1DeltaM", "O1ThetaStd", "O1ThetaM", "O1AlphaStd", "O1AlphaM", "O1BetaStd", "O1BetaM", "O2DeltaStd", "O2DeltaM", "O2ThetaStd", "O2ThetaM", "O2AlphaStd", "O2AlphaM", "O2BetaStd", "O2BetaM", "P8DeltaStd", "P8DeltaM", "P8ThetaStd", "P8ThetaM", "P8AlphaStd", "P8AlphaM", "P8BetaStd", "P8BetaM", "T8DeltaStd", "T8DeltaM", "T8ThetaStd", "T8ThetaM", "T8AlphaStd", "T8AlphaM", "T8BetaStd", "T8BetaM", "FC6DeltaStd", "FC6DeltaM", "FC6ThetaStd", "FC6ThetaM", "FC6AlphaStd", "FC6AlphaM", "FC6BetaStd", "FC6BetaM", "F4DeltaStd", "F4DeltaM", "F4ThetaStd", "F4ThetaM", "F4AlphaStd", "F4AlphaM", "F4BetaStd", "F4BetaM", "F8DeltaStd", "F8Delta_m", "F8ThetaStd", "F8ThetaM", "F8AlphaStd", "F8AlphaM", "F8BetaStd", "F8BetaM", "AF4DeltaStd", "AF4DeltaM", "AF4ThetaStd", "AF4ThetaM", "AF4AlphaStd", "AF4AlphaM", "AF4BetaStd", "AF4BetaM"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
usera = readtable("D:\SEM_6\BCI\Assignment02\archive\Dataset\user_a.csv", opts);

% Convert to output type
usera = table2array(usera);

% Clear temporary variables
clear opts

%% Data changing

classes = usera(:,1);
data = [];
for i = 2:2:length(usera(1,:))
    temp = (usera(:,i)).^2 + (usera(:,i+1)).^2;
    data = [data temp];
end
X = [data classes];
clear data usera classes temp

%% Data training
[Classifier, acc] = trainClassifier(X);
print("Accuracy of ID3 classification tree");
print(acc);